author: Anders Holmgren <andersmholmgren@gmail.com>
description: A micro framework for modern web apps built from the ground up on the shelf framework
homepage: https://bitbucket.org/andersmholmgren/mojito
name: mojito
version: 0.6.3
dependencies: 
  http_exception: '^0.1.0'
  matcher: '>=0.10.0 <0.13.0'
  oauth: '>=0.3.0 <0.4.0'
  option: '>=0.3.0 <2.0.0'
  shelf: '^0.6.4+2'
  shelf_auth: '>=0.7.0 <0.7.1'
  shelf_auth_session: '>=0.4.9 <0.4.10'
  shelf_bind: '^0.9.1'
  shelf_exception_handler: '^0.1.0'
  shelf_oauth: '>=0.8.0 <0.8.1'
  shelf_oauth_memcache: '^0.3.5'
  shelf_path: '^0.1.7'
  shelf_proxy: '^0.1.0+2'
  shelf_rest: '>=0.3.2 <0.3.3'
  shelf_static: '^0.2.2'
  config: '^0.0.3'
  quiver: '^0.20.0'
dependency_overrides:
dev_dependencies: 
  mockito: '>=0.8.1 <0.11.0'
  test: '^0.12.0'
  stream_transformers: "^0.3.0+3"
environment: 
  sdk: '>=1.9.0 <2.0.0'
