author: Anders Holmgren <andersmholmgren@gmail.com>
description: A micro framework for modern web apps built from the ground up on the shelf framework
homepage: https://bitbucket.org/andersmholmgren/mojito
name: mojito
version: 0.5.2
dependencies: 
  http_exception: '^0.1.0'
  matcher: '>=0.10.0 <0.13.0'
  oauth: '>=0.3.0 <0.4.0'
  option: '>=0.3.0 <2.0.0'
  shelf: '^0.6.0'
  shelf_exception_handler: '^0.1.0'
  shelf_proxy: '^0.1.0+2'
  shelf_static: '^0.2.2'
  shelf_auth: 
    git: 
      ref: e2448c42bc1e6f8488777c4c0c7ce364edde1c70
      url: git@bitbucket.org:andersmholmgren/shelf_auth.git
  shelf_auth_session: 
    git: 
      ref: e12b06d07c8819ad4836914169b81bff4280e359
      url: git@bitbucket.org:andersmholmgren/shelf_auth_session.git
  shelf_bind: 
    git: 
      ref: 9cd289ef1c75a992f90db0425e53009f50605a7b
      url: git@bitbucket.org:andersmholmgren/shelf_bind.git
  shelf_oauth: 
    git: 
      ref: 24ef30a5d3b80fa20367ead869dc076129cf6ac9
      url: git@bitbucket.org:andersmholmgren/shelf_oauth.git
  shelf_oauth_memcache: 
    git: 
      ref: adae7cb9f77c7729ce2e7e21da52dc68740152f8
      url: git@bitbucket.org:andersmholmgren/shelf_oauth_memcache.git
  shelf_path: 
    git: 
      ref: 7c910514e97cfd2aa47f0d1ba8733b00d925578a
      url: git@bitbucket.org:andersmholmgren/shelf_path.git
  shelf_rest: 
    git: 
      ref: f5726d6a9710714f027052a5aa8761dd85cedd94
      url: git@bitbucket.org:andersmholmgren/shelf_rest.git
dependency_overrides: 
dev_dependencies: 
  mockito: '>=0.8.1 <0.11.0'
  test: '^0.12.0'
environment: 
  sdk: '>=1.9.0 <2.0.0'
