name: mojito
version: 0.0.1
author: Anders Holmgren <andersmholmgren@gmail.com>
description: A micro framework for modern web apps built from the ground up on the shelf framework
homepage: https://bitbucket.org/andersmholmgren/shelf_auth
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  option: '>=0.3.3 <0.4.0'
  shelf: any
  shelf_auth: '>=0.2.2'
  shelf_bind: any
  shelf_exception_response: any
  shelf_path: any
  shelf_proxy: any
  shelf_rest: '>=0.1.4-pre.4'
  shelf_route: '>=0.10.1'
dev_dependencies:
  mockito: any
  unittest: any
