author: Anders Holmgren <andersmholmgren@gmail.com>
description: A micro framework for modern web apps built from the ground up on the shelf framework
homepage: https://bitbucket.org/andersmholmgren/mojito
name: mojito
version: 0.2.0
dependencies: 
  oauth: '>=0.3.0 <0.4.0'
  option: '>=0.3.3 <0.4.0'
  shelf: '>=0.5.5+1 <0.6.0'
  shelf_auth_session: '>=0.1.0 <0.1.1'
  shelf_exception_response: '>=0.1.1 <0.2.0'
  shelf_oauth: '>=0.4.0 <0.4.1'
  shelf_path: '>=0.1.1+1 <0.2.0'
  shelf_proxy: '>=0.1.0+1 <0.2.0'
  shelf_static: '>=0.2.1 <0.3.0'
  shelf_auth: 
    path: /Users/blah/dart/newbacklogio/gitbacklog_root/gissue_root/shelfish_root/shelf_auth
  shelf_bind: 
    path: /Users/blah/dart/newbacklogio/gitbacklog_root/gissue_root/shelfish_root/shelf_bind
  shelf_rest: 
    path: /Users/blah/dart/newbacklogio/gitbacklog_root/gissue_root/shelfish_root/shelf_rest
  shelf_route: 
    path: /Users/blah/dart/newbacklogio/gitbacklog_root/gissue_root/shelfish_root/shelf_route
dependency_overrides: 
dev_dependencies: 
  mockito: '>=0.8.1 <0.9.0'
  unittest: '>=0.11.0+5 <0.12.0'
environment: 
  sdk: '>=1.2.0 <2.0.0'
