name: mojito
version: 0.0.1+1
author: Anders Holmgren <andersmholmgren@gmail.com>
description: A micro framework for modern web apps built from the ground up on the shelf framework
homepage: https://bitbucket.org/andersmholmgren/mojito
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  oauth: any
  option: '>=0.3.3 <0.4.0'
  shelf: '>=0.5.5 <0.6.0'
  shelf_auth:
    path: ../shelf_auth
  shelf_bind: '>=0.7.0 <0.8.0'
  shelf_exception_response:
    git: https://github.com/Andersmholmgren/shelf_exception_response.git
  shelf_path: '>=0.1.1+1 <0.2.0'
  shelf_proxy: '>=0.1.0+1 <0.2.0'
  shelf_rest:
    path: ../shelf_rest
  shelf_route: '>=0.10.1 <0.11.0'
dev_dependencies:
  mockito: any
  unittest: any
dependency_overrides:
  shelf_auth:
    path: ../shelf_auth
  shelf_rest:
    path: ../shelf_rest
