author: Anders Holmgren <andersmholmgren@gmail.com>
description: A micro framework for modern web apps built from the ground up on the shelf framework
homepage: https://bitbucket.org/andersmholmgren/mojito
name: mojito
version: 0.2.0
dependencies: 
  http_exception: '^0.1.0'
  oauth: '>=0.3.0 <0.4.0'
  option: '>=0.3.3 <0.4.0'
  shelf: '^0.6.0'
  shelf_exception_handler: '^0.1.0'
  shelf_path: '^0.1.2'
  shelf_proxy: '^0.1.0+2'
  shelf_static: '^0.2.2'
  shelf_auth: 
    git: 
      ref: 54413bb580079eee5ed5020bc59acf7ea93f86c7
      url: git@bitbucket.org:andersmholmgren/shelf_auth.git
  shelf_auth_session: 
    git: 
      ref: 6af967368b8f92df6861ddc53322581e6e55d40b
      url: git@bitbucket.org:andersmholmgren/shelf_auth_session.git
  shelf_bind: 
    git: 
      ref: 5e9e2bb0b0fd43593c319ca2f7d8c82e6e51f537
      url: git@bitbucket.org:andersmholmgren/shelf_bind.git
  shelf_oauth: 
    git: 
      ref: 96e49539d1fd4cccee16dd6af8d908ff76494ce1
      url: git@bitbucket.org:andersmholmgren/shelf_oauth.git
  shelf_rest: 
    git: 
      ref: 6c9274aa03eb36fb2c930e12bf3f482f0e283132
      url: git@bitbucket.org:andersmholmgren/shelf_rest.git
  shelf_route: 
    git: 
      ref: b30ca195ff32d37cb310ee348ac59acde7a1c005
      url: git@bitbucket.org:andersmholmgren/shelf_route.git
dependency_overrides: 
dev_dependencies: 
  mockito: '>=0.8.1 <0.9.0'
  unittest: '>=0.11.0+5 <0.12.0'
environment: 
  sdk: '>=1.9.0 <2.0.0'
