author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A micro framework for modern web apps built from the ground up on the shelf framework"
homepage: "https://bitbucket.org/andersmholmgren/mojito"
name: "mojito"
version: "0.6.5"
dependencies: 
  config: ">=0.0.5 <0.0.6"
  http_exception: "^0.1.0"
  matcher: ">=0.10.0 <0.13.0"
  oauth: ">=0.3.0 <0.4.0"
  option: "^1.1.0"
  quiver: ">=0.21.4 <0.22.0"
  shelf: "^0.6.4+2"
  shelf_auth: ">=0.7.2 <0.7.3"
  shelf_auth_session: ">=0.4.11 <0.4.12"
  shelf_bind: "^0.9.3"
  shelf_exception_handler: "^0.1.0"
  shelf_oauth: ">=0.8.2 <0.8.3"
  shelf_oauth_memcache: "^0.3.7"
  shelf_path: "^0.1.8"
  shelf_proxy: "^0.1.0+2"
  shelf_rest: ">=0.3.4 <0.3.5"
  shelf_static: "^0.2.2"
dev_dependencies: 
  mockito: ">=0.11.0 <0.12.0"
  stream_transformers: "^0.3.0+3"
  test: "^0.12.0"
environment: 
  sdk: ">=1.9.0 <2.0.0"
