author: "Anders Holmgren <andersmholmgren@gmail.com>"
description: "A micro framework for modern web apps built from the ground up on the shelf framework "
homepage: "https://bitbucket.org/andersmholmgren/mojito"
name: "mojito"
version: "0.6.5"
dependencies:
  config: ">=0.0.5 <0.0.6"
  http_exception: "^0.1.0"
  matcher: ">=0.10.0 <0.13.0"
  option: "^1.1.0"
  quiver: ">=0.21.4 <0.22.0"
  shelf: "^0.6.4+2"
  shelf_bind: "^0.9.3"
  shelf_path: "^0.1.8"
  shelf_proxy: "^0.1.0+2"
  shelf_rest: ">=0.3.4 <0.3.5"
  shelf_static: "^0.2.2"
  xml: '>=2.1.0 <3.0.0'
environment:
  sdk: ">=1.9.0 <2.0.0"
